### ISSUE TITLE
Cannot scroll

### ISSUE THREAD

**Issue by volfco** [ritstudentgovernment/sg.rit.edu#6]
After you login, you can no longer scroll. You have to reload the page to get scrolling back. Happens in Safari 7 and Firefox 39.

See this lovely GIF: https://gfycat.com/SkeletalComfortableCarp

**Comment by petermikitsh** [comment]
The login modal doesn't close properly after successful authentication. The `modal-open` class remains on the `<body>`. I'll investigate further; thanks for the report.

**Comment by petermikitsh** [comment]
Patch is in release v1.0.0.1.
